### PR TITLE
Using explicit options

### PR DESCRIPTION
**Pull request by nfroidure**
As discussed here https://github.com/sindresorhus/gulp-filter/issues/29 , an attempt to make restore stream creation optionnal.

### CODE REVIEW

**Comment by nfroidure** [comment]
I don't like this API that much since it is a bit verbose:
```js
var filterAlone = filter('/**/*');
var filterWithRestoreAsPassthrough = filter('/**/*', {restore: true});
var filterWithRestoreAsReadable = filter('/**/*', {restore: true, passthrough: false});
```
As told earlyer, `{restore: true}` could be implied by `{passthrough: false}`, but tricky imo.

No more idea except this geeky one using bit bashing, but looks like it is not less verbose:
```js
assert(filter.RESTORE == parseInt('01', 2));
assert(filter.READABLE_RESTORE == parseInt('11', 2));

var filterAlone = filter('/**/*');
var filterWithRestore = filter('/**/*', filter.RESTORE);
var filterWithRestoreAndPassthrough = filter('/**/*', filter.READABLE_RESTORE);
```

I'm also wondering wich combination is the most used:
1 - filter only
2 - restore as passthrough
3 - restore as readable

I hesitate between 1 & 2. That said, i'm actually often using 3 when i combine restored stream with StreamQueue.

What are you using the most ?

**Comment by nfroidure** [comment]
@sindresorhus what about it?

**Comment by sindresorhus** [comment]
Sorry about the looong delay. Been busy and completely forgot about this...

I think the options style makes more sense.

> I'm also wondering wich combination is the most used:

Mostly `1`, and sometimes `2`, but never `3`.

-

`passthrough` and `restore` options sounds good to me. Gulp also went with a `passthrough` options: https://github.com/wearefractal/vinyl-fs/blob/c0162156cd3f597a030f906114566c06b6d73942/lib/src/index.js#L24 (maybe some of the code can be of inspiration). Though it doesn't make a lot of sense to have the `passthrough` option on the main function if it applies only to the `filter` stream.

**Comment by Delagen** [comment]
I think instead of
`
through.obj()
`
better write
`
through({objectMode:true}) 
`
the shorthand sometime working unpredictable

**Comment by sindresorhus** [comment]
@Delagen No, that would just hide the actual problem.

**Comment by sindresorhus** [comment]
@nfroidure Friendly ping :)

**Comment by nfroidure** [comment]
@sindresorhus friendly pong ;)

I just improved tests and applied your default options flavor.

**Comment by sindresorhus** [comment]
@nfroidure Excellent :) A couple of minor comments and we're there.

**Comment by nfroidure** [comment]
Done. Thanks for the review.

**Comment by sindresorhus** [comment]
Landed! Woot. Thanks again @nfroidure :)

**Comment by sindresorhus** [comment]
Release notes: https://github.com/sindresorhus/gulp-filter/releases/tag/v3.0.0

@nfroidure Feel free to edit if something is incorrect or could have been written better ;)

**Pull request closed without merging**
