### PR TITLE
Fix behavior for matching paths outside cwd

### LINKED ISSUE #85: Filtering files with paths outside of gulp folder not possible?
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/gulp-filter/issues/85)

hi,
it seems that currently gulp-filter does not support filtering files with paths outside of the folder the gulp.task is running in.
if the current behavior is desired an options to allow other paths as well would be nice (as done by del package for example).
thanks & regards,
Marcel

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#92 fix behavior for matching paths outside cwd](https://issuehunt.io/r/sindresorhus/gulp-filter/pull/92)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/gulp-filter/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### LINKED ISSUE #87: Gulp filter filters everything
Version 5.0.0 works ok, version 5.0.1 broken.
Looks like a change was made between 5.0.0 and 5.0.1 and now filter just skips everything.
Here's a simplified code snippet which:

    function(svn_revision){
        var xmlFilter = filter("../**/*.xml", {restore: true});

        return gulp.src([
                "../Setup/Installed/Data/Http/Templates/**/*",
            ], { base : '../' })
            .pipe(xmlFilter)
            .pipe(replace('@PRODUCT_SVN_BUILD@', svn_revision))
            .pipe(xmlFilter.restore)
            .pipe(gulp.dest("../BinRepo/Templates"));
    },

Expected behavior: All xml files should have @PRODUCT_SVN_BUILD@ replaced.
Actual behavior: Looks like they're just written to dest folder.

### PR DESCRIPTION
**Pull request by maximelkin**
Fixes #85 (not sure, maybe #87 too)
Here breaking changes:
Old behavior:
all paths, which is outside of current working directory, should be matched only by absolute path glob

New behavior:
you can match dirs outside current working dir
if you want match globally - start glob pattern with /

Removed test "should filter relative paths that leave current directory tree", because of breaking change

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#85: Filtering files with paths outside of gulp folder not possible?](https://issuehunt.io/repos/15827909/issues/85)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by maximelkin** [comment]
Should be logic of detecting absolute/relative path go in minimatch instead?

**Comment by sindresorhus** [comment]
Sorry, seems I missed this one.

**Comment by sindresorhus** [comment]
Can you explain exactly what the breaking change is? What used to work and will no longer work (from a user's perspective)?

**Comment by maximelkin** [comment]
I will return to PR in two weeks

**Comment by sindresorhus** [comment]
Bump

**Comment by maximelkin** [comment]
Got stuck at
```js
minimatch.match('/A/B/C/d.js', '!/**/test.js') -> false
```

**Comment by maximelkin** [comment]
Got what, tried to exclude from empty set of dirs

**Comment by maximelkin** [comment]
@sindresorhus described changes in test cases, most of them failing on old version

**Pull request merged**
